### ISSUE TITLE
Please count just the active ones

### ISSUE THREAD

**Issue by olvier** [schech1/uptime-buddy#11]
Hey, and thank you for the great app!

For lower heartrate, i would appreciate, to just count the actives services.
Historically i have 33 services, but just 15 active ones.
The other one are paused/deactivated, until i need them again (for example 6 security cameras).

Would it be possible to implement? :)

Best regards

**Comment by schech1** [comment]
Hey, 
thank you :-)
Great idea.
I can make another complication to choose from, which shows only the active ones.
Which complication you currently use the most?

Would you still like the number to turn red, when not all services are online or just a plain number?

Regards,
Christoph

**Comment by olvier** [comment]
Stupid question: does somebody need monitoring disabled services? 

To your question: you have placed a colored symbol, maybe this is enough? :)
I like the white number, too, but maybe try one comlication with colored numbers :)
But i dont know which one, started today with your app, doesnt have placed any complication for now. This is the next step.

**Comment by schech1** [comment]
Ah, i know what you mean.
I will check within the next week, if I get figure out paused services and add an option to exclude them.

Will update this issue, when I have something to show 🙂

**Comment by olvier** [comment]
Maybe there is not that much to do.
There is somewhere already a counter for active and disabled ones.
Hopefully you can work with already defined `$VARs`.

<img width="444" alt="image" src="https://github.com/user-attachments/assets/5415571a-c815-48fa-bb61-95d55ffca6ff">

**Comment by schech1** [comment]
A new app version is on the way.
I added an option to show or exclude paused monitors in the list.
Complications will only count active monitors.

This change will also require to pull the latest docker image. 
I will merge the changes to the backend, when the app is approved for the App Store.

Thanks for the input and feel free to test the changes and let me know if there are any issues.

**Comment by schech1** [comment]
Done with commit 671630a6c744712208996bfca26479feae0ccc5b

Please reopen a new issue in case of any problems.
