### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by serafearz** [schech1/uptime-buddy#15]
Hello,

The docker instance will run for 2 seconds then stops giving the below error:

uptime-buddy-api-1  | Traceback (most recent call last):
uptime-buddy-api-1  |   File "/usr/local/lib/python3.11/site-packages/uptime_kuma_api/api.py", line 667, in connect
uptime-buddy-api-1  |     self.sio.connect(f'{self.url}/socket.io/', wait_timeout=self.timeout, headers=self.headers)
uptime-buddy-api-1  |   File "/usr/local/lib/python3.11/site-packages/socketio/client.py", line 159, in connect
uptime-buddy-api-1  |     raise exceptions.ConnectionError(exc.args[0]) from None
uptime-buddy-api-1  | socketio.exceptions.ConnectionError: HTTPConnectionPool(host='45.155.76.186', port=3001): Max retries exceeded with url: /socket.io/?transport=polling&EIO=4&t=1725743804.1397467 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f61ab83e3d0>, 'Connection to x.x.x.x timed out. (connect timeout=5)'))
uptime-buddy-api-1  |
uptime-buddy-api-1  | During handling of the above exception, another exception occurred:
uptime-buddy-api-1  |
uptime-buddy-api-1  | Traceback (most recent call last):
uptime-buddy-api-1  |   File "/app/app.py", line 171, in <module>
uptime-buddy-api-1  |     main = Main()
uptime-buddy-api-1  |            ^^^^^^
uptime-buddy-api-1  |   File "/app/app.py", line 13, in __init__
uptime-buddy-api-1  |     self.configure_api_client()
uptime-buddy-api-1  |   File "/app/app.py", line 33, in configure_api_client
uptime-buddy-api-1  |     self.api = UptimeKumaApi(self.UPTIME_KUMA_URL)
uptime-buddy-api-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uptime-buddy-api-1  |   File "/usr/local/lib/python3.11/site-packages/uptime_kuma_api/api.py", line 510, in __init__
uptime-buddy-api-1  |     self.connect()
uptime-buddy-api-1  |   File "/usr/local/lib/python3.11/site-packages/uptime_kuma_api/api.py", line 669, in connect
uptime-buddy-api-1  |     raise UptimeKumaException("unable to connect")
uptime-buddy-api-1  | uptime_kuma_api.exceptions.UptimeKumaException: unable to connect
root@icecream:/home/fearz/uptimemate# telnet localhost 3001
Trying ::1...
Connected to localhost.
Escape character is '^]'.
^CConnection closed by foreign host.
root@icecream:/home/fearz/uptimemate# ^C
root@icecream:/home/fearz/uptimemate# telnet x.x.x.x 3001
Trying x.x.x.x....
Connected to x.x.x.x.
Escape character is '^]'.
^CConnection closed by foreign host.
root@icecream:/home/fearz/uptimemate#

**Comment by schech1** [comment]
Hey,
Are you sure your Uptime Kuma instance is reachable?

_HTTPConnectionPool(host='45.155.76.186', port=3001):_

Is this a local IP? Are you sure it's correct?
The error looks like the backend does not get any response from the  address you provided.

**Comment by schech1** [comment]
I will close it for now.
If the issue persists, please open a new issue
