### ISSUE TITLE
can't login with 2fa code

### ISSUE THREAD

**Issue by Raxiel1987** [schech1/uptime-buddy#16]
i've setup the uptime buddy the backend is ok but when i add the 2fa code says it's incorrect, but in uptime kuma works..
i've to configure the timezone? or something else?

**Comment by schech1** [comment]
Hey,
You have enabled MFA=true in your docker-compose?
Please restart the container, then start the iOS-App, enter backend, token and the 2FA code.
And then please provide the docker logs.

Stupid question: You made sure that you apply the 2FA code before it expires?

Regards,
Christoph
