### ISSUE TITLE
Support for MFA

### ISSUE THREAD

**Issue by PhoenixSheppy** [schech1/uptime-buddy#2]
Please add support for MFA Tokens.

I personally use MFA tokens on my Uptime-Kuma instance, and had to disable them to implement uptime-buddy.

Also, Uptime-Kuma has support for API Keys, consider implementing those instead.

Thank you.

**Comment by ivolanski** [comment]
+1 for API keys

**Comment by schech1** [comment]
Hey,
if you would like to give it a try, I made an experimental version with 2FA support.
You can use the public TestFlight invitation for the app:
https://testflight.apple.com/join/okTxZGX1

Use the docker experimental tag for the backend. 
`schech1/uptime-buddy-api:experimental`

Add this env var to your docker compose

`- MFA=True`

**Comment by vercas** [comment]
I can confirm that it works.

**Comment by schech1** [comment]
Great, thanks for the feedback.
I also had it running for a while now without issues.
Will merge it and publish a new app version soon.
