### ISSUE TITLE
Apple watch, showing all green for down services

### ISSUE THREAD

**Issue by user987098** [schech1/uptime-buddy#25]
My widget shows 23/26 online, but when I click it and open the app on watch,the menu that you scroll through shows all entries as green, so I had to click into each until I found the ones that are red.

Please make the initial Apple Watch menu show coloring based on if the service is up or down

**Comment by user987098** [comment]
The menu in image 5 of readme is what I am talking about. They should look like the top red entry, but instead they are shown like all the green entries below

**Comment by schech1** [comment]
Hmm.. that's weird.
Offline monitors should appear red in the list.
I will take a look tomorrow.
Maybe something got messed up with a merge.
Thanks for the hint

**Comment by schech1** [comment]
Found the issue. 
I messed up something, when I gave the app a makeover in the last update.
Fixed it with a new app update.
Should be available in a few hours, once it got approved by Apple.
