### ISSUE TITLE
Support no auth 

### ISSUE THREAD

**Issue by johntdyer** [schech1/uptime-buddy#4]
My uptime kuma is on my private network so I dont use auth on it... you're app seems to not work unless I have auth enabled which is problematic

**Comment by schech1** [comment]
Hey,
thank you for the hint.
I will fix that in the next version.

**Comment by schech1** [comment]
That was an easy one.
Fixed it. 
Just pull the latest image and remove those two lines from the compose file:

```
 - USERNAME=YOUR_UPTIME_KUMA_USERNAME
 - PASSWORD=YOUR_UPTIME_KUMA_PASSWORD 
 ```

Thanks for your request.
