### ISSUE TITLE
Backend not reachable

### ISSUE THREAD

**Issue by ivolanski** [schech1/uptime-buddy#6]
Hi, 
If I try https://s.d.com//monitor/1/beats?token=????? it works well and show json data, but my apple watch has back end not reachable message.
Token is the same, url is the same, no port or with port, http or https ..... I already did multiple tests with no lucky

Thanks

**Comment by schech1** [comment]
Hey,
that's hard to analyze from here.
So, the backend seems to work.
You have it locally or exposed the backend to the internet?

Have you tried to send the settings again?
Token and url in the info screen of the Watch app is correct?

Do you see any logs in the docker container, when you open the app or refresh?

**Comment by ivolanski** [comment]
Hi, thanks for your reply, 

I know it's hard to guess without so much information, the same for me....

You have it locally or exposed the backend to the internet?
internet

Have you tried to send the settings again?
many times and many possibilities like http, https, explicit port 80, 443 or with no port information.....

Token and url in the info screen of the Watch app is correct?
can't read url entirely but looks like ok

Do you see any logs in the docker container, when you open the app or refresh?
yes when testing from web browser
no when trying from apple watch
```
192.168.50.205 - - [16/Jun/2024 17:06:14] "GET / HTTP/1.1" 404 -

172.28.0.1 - - [16/Jun/2024 17:07:22] "GET / HTTP/1.1" 404 -

192.168.50.205 - - [16/Jun/2024 17:09:29] "GET /status HTTP/1.1" 403 -

192.168.50.205 - - [16/Jun/2024 17:13:39] "GET /status?token=ac45mr HTTP/1.1" 200 -

172.28.0.1 - - [16/Jun/2024 17:14:14] "GET /status?token=ac45mr HTTP/1.1" 200 -

172.28.0.1 - - [16/Jun/2024 17:14:14] "GET /favicon.ico HTTP/1.1" 404 -

172.28.0.1 - - [16/Jun/2024 17:14:39] "GET /monitors?token=ac45mr HTTP/1.1" 200 -

172.28.0.1 - - [16/Jun/2024 17:15:39] "GET /monitor/1/beats?token=ac45mr HTTP/1.1" 200 -

172.28.0.1 - - [16/Jun/2024 17:17:49] "GET /monitor/1/beats?token=ac45mr HTTP/1.1" 200 -

172.28.0.1 - - [16/Jun/2024 17:24:07] "GET /monitor/1/beats?token=ac45mr HTTP/1.1" 200 -

172.28.0.1 - - [16/Jun/2024 17:24:07] "GET /favicon.ico HTTP/1.1" 404 -

172.28.0.1 - - [16/Jun/2024 17:55:53] "GET /monitor/1/beats?token=ac45mr HTTP/1.1" 200 -

172.28.0.1 - - [16/Jun/2024 17:58:54] "GET /monitor/1/beats?token=ac45mr HTTP/1.1" 200 -

172.28.0.1 - - [16/Jun/2024 17:58:54] "GET /favicon.ico HTTP/1.1" 404 -
```

**Comment by ivolanski** [comment]
@schech1 if you have any contact that you fell comfortable to share email, telegram.... I can send you my url and api key so you can test it in your side, maybe it's something related to apple watch version, network type.... I don't know

**Comment by schech1** [comment]
You can sent me a PM on reddit.
I opened this topic:

https://www.reddit.com/r/selfhosted/s/aX8v4Zi58o

I would really like to take a look.

But I also now thought, that I will implement a backend check already in the iOS-App that can show helpful error messages, before sending it to watch.

**Comment by schech1** [comment]
App version 1.0.4 has now a backend check with proper error messages in the iOS app.
@ivolanski  If you have any more hints what caused the issue, feel free to post it here.

**Comment by schech1** [comment]
Closing for now. Could not be reproduced.
